-- Categoría temática en la BD (no en código).
-- category = principal (ya existía la columna); categories = todas (principal + secundarias).
ALTER TABLE norms ADD COLUMN IF NOT EXISTS categories text[] NOT NULL DEFAULT '{}';

UPDATE norms n SET category = m.cat, categories = m.cats
FROM (VALUES
  ('constitucion-nacional','constitucional', ARRAY['constitucional']),
  ('const-buenos-aires','constitucional', ARRAY['constitucional']),
  ('const-caba','constitucional', ARRAY['constitucional']),
  ('const-catamarca','constitucional', ARRAY['constitucional']),
  ('const-chaco','constitucional', ARRAY['constitucional']),
  ('const-chubut','constitucional', ARRAY['constitucional']),
  ('const-cordoba','constitucional', ARRAY['constitucional']),
  ('const-corrientes','constitucional', ARRAY['constitucional']),
  ('const-entre-rios','constitucional', ARRAY['constitucional']),
  ('const-formosa','constitucional', ARRAY['constitucional']),
  ('const-jujuy','constitucional', ARRAY['constitucional']),
  ('const-la-pampa','constitucional', ARRAY['constitucional']),
  ('const-la-rioja','constitucional', ARRAY['constitucional']),
  ('const-mendoza','constitucional', ARRAY['constitucional']),
  ('const-misiones','constitucional', ARRAY['constitucional']),
  ('const-neuquen','constitucional', ARRAY['constitucional']),
  ('const-rio-negro','constitucional', ARRAY['constitucional']),
  ('const-salta','constitucional', ARRAY['constitucional']),
  ('const-san-juan','constitucional', ARRAY['constitucional']),
  ('const-san-luis','constitucional', ARRAY['constitucional']),
  ('const-santa-cruz','constitucional', ARRAY['constitucional']),
  ('const-santa-fe','constitucional', ARRAY['constitucional']),
  ('const-santiago-del-estero','constitucional', ARRAY['constitucional']),
  ('const-tierra-del-fuego','constitucional', ARRAY['constitucional']),
  ('const-tucuman','constitucional', ARRAY['constitucional']),
  ('codigo-penal','penal', ARRAY['penal']),
  ('ley-27150','penal', ARRAY['penal','procesal-penal']),
  ('ley-22278','penal', ARRAY['penal','ninez']),
  ('ley-27801','penal', ARRAY['penal','ninez']),
  ('ley-20744','laboral', ARRAY['laboral']),
  ('ley-11544','laboral', ARRAY['laboral']),
  ('ley-27802','laboral', ARRAY['laboral']),
  ('decreto-315-2026','laboral', ARRAY['laboral','tributario']),
  ('rg-arca-5844-2026','laboral', ARRAY['laboral','tributario']),
  ('decreto-407-2026','laboral', ARRAY['laboral']),
  ('codigo-civil-comercial','civil', ARRAY['civil','comercial','consumidor']),
  ('codigo-aduanero','aduanero', ARRAY['aduanero','tributario','comercial']),
  ('ley-25326','datos-personales', ARRAY['datos-personales','transparencia']),
  ('disp-dnpdp-7-2005','datos-personales', ARRAY['datos-personales']),
  ('ley-27275','transparencia', ARRAY['transparencia']),
  ('ley-26639','ambiental', ARRAY['ambiental']),
  ('decreto-207-2011','ambiental', ARRAY['ambiental']),
  ('ley-27499','genero', ARRAY['genero']),
  ('ley-26743','genero', ARRAY['genero','salud','derechos-humanos']),
  ('ley-26618','genero', ARRAY['genero','civil']),
  ('ley-26485','genero', ARRAY['genero','derechos-humanos']),
  ('ley-27610','genero', ARRAY['genero','salud']),
  ('ley-26657','salud', ARRAY['salud','derechos-humanos']),
  ('ley-27642','salud', ARRAY['salud','consumidor']),
  ('decreto-151-2022','salud', ARRAY['salud']),
  ('ley-24240','consumidor', ARRAY['consumidor']),
  ('ley-26061','ninez', ARRAY['ninez','derechos-humanos']),
  ('convencion-derechos-nino','ninez', ARRAY['ninez','internacional','derechos-humanos']),
  ('ley-26206','educacion', ARRAY['educacion']),
  ('carta-onu','internacional', ARRAY['internacional','derechos-humanos']),
  ('ley-26842','derechos-humanos', ARRAY['derechos-humanos','penal']),
  ('ley-23592','derechos-humanos', ARRAY['derechos-humanos','penal']),
  ('ley-27742','economico', ARRAY['economico','laboral','tributario','ambiental'])
) AS m(id, cat, cats)
WHERE n.id = m.id;
